---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: netdata
spec:
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  refreshInterval: 15m
  target:
    name: netdata-secret
    template:
      engineVersion: v2
      data:
        NETDATA_CLAIM_TOKEN: "{{ .NETDATA_CLAIM_TOKEN }}"
  dataFrom:
  - extract:
      key: netdata