---
# yaml-language-server: $schema=https://lds-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: netdata
spec:
  interval: 30m
  chart:
    spec:
      chart: netdata
      sourceRef:
        kind: HelmRepository
        name: netdata
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: external-secrets
      namespace: external-secrets
  values:
    child:
      claiming:
        enabled: true
        rooms: 7643ea3f-77dc-4f8f-b5dd-0f7dc1e65a9e
      envFrom:
        - secretRef:
            name: netdata-secret
    parent:
      claiming:
        enabled: true
        rooms: 7643ea3f-77dc-4f8f-b5dd-0f7dc1e65a9e
      envFrom:
        - secretRef:
            name: netdata-secret
    ingress:
      enabled: true
      annotations:
        kubernetes.io/tls-acme: "true"
      path: /
      pathType: Prefix
      hosts:
        - "{{ .Release.Name }}.${SECRET_DOMAIN}"
      spec:
        ingressClassName: internal