---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  # Probably need to rename this to something like "themepark" without a - in the name
  #- ../../../../templates/gatus/guarded