---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kubelet-csr-approver
spec:
  interval: 30m
  chart:
    spec:
      chart: kubelet-csr-approver
      version: 1.2.2
      sourceRef:
        kind: HelmRepository
        name: postfinance
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    providerRegex: ^(pw-talos-01|pw-talos-02|pw-talos-03)$
    bypassDnsResolution: true
    metrics:
      enable: true
      serviceMonitor:
        enabled: true
