apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_EXAMPLE: ENC[AES256_GCM,data:CUxyHH1WGUCLsRNeNtKF5h4xMwMduKJnhpY9cXUczRGrnsX3dvYD6AnkjxTGyneYW6wj8rRs1iebBdLBgwcsCIvNHkyKK3ynOrWwuwhvWFPXi+waSskbAHAQCErWsg==,iv:bBhe5fHdW6dBQECxedCLJDWFrIvmOfoeKwxKGW0abg8=,tag:yGIZwfFlm1CrMGDLCf3SOg==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:Yyj7ft703/zQg4vSIQ==,iv:v2/mCIOscb6Q7q9zzTeCtc8EqN4+O11jx1xM9dsnBDo=,tag:WSDXaoTS9U36q+zItdEtNw==,type:str]
    SECRET_INTERNAL_DOMAIN: ENC[AES256_GCM,data:UzB7ms136vN89VgM0Z5OZ23m,iv:3FEPho8+HrcvtVowOA4nWIRRU3A0dOOAbuC1oa33b1o=,tag:3BuxZQ1SRuM6f1v54KJbsw==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:BZhbGd82Nxc9D4t1V+VdW5e7H8hm,iv:PxeRQ46dk1TN19y8fL1dOL7Qh7a1f0nqME0D9q8xfyk=,tag:JhWLPpMK/QA1G8rUK9qShw==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:nM0fj1K61truQbfFn0bDJY7EqxecyIpQrzB1VyHZ7025+G6d,iv:BLpIH2J2Wz0SqnCq3G8un2UDCJYRL7D9jH3K/0POypM=,tag:NdLZZyXCbYbDWUvZGQGm3g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1uu6l38vuhpts52zm7vncjtcr34cg2nqqeyree7qvl59jlfez55asjm64pm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3bVU4Q3pVSXFnNlJhUUZm
            akVPRmlkT0tPL2M0S0dxNktaWlcrNmZVTEIwCnFjczMrVnljT1hLdUNvVnNpZkhQ
            K2cwZHB2RGVoRFlmb21BU2s4cVdXUWsKLS0tIGxPNE9RSzMxTjAzS0Yrc2ZRZlYz
            dkRxQ2t5aEQ4VE5mVTVkbTJYQklMM2MKcN1d1hHF+ffEUWQUyiSYCtqihM0cvrM/
            kQm/C7qtANA2lkyta1YiEk/T3y/OTIRinuMI+V0NQjQabMzPiftEuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-04-10T10:53:41Z"
    mac: ENC[AES256_GCM,data:8WLjPaGS9ELbuOgtqrUdBqoPuAtfrrsb3Rsp4jeJwJu01Toj/uBCoAzi1skxIn7BWnUjDQ7PUV9RojXMZurD0Sb4jtCs+R1eB7ycaalLlDLpjMBrJXN62gUoE1IsQw4e41vnHW4S9k11k/4nNO4750utCjQVk04l48bK5OE/enc=,iv:TuJ2ZaUmis1g0TT76SPp/7MnnPjWUGPUCpGibifU8tg=,tag:0Tco2BTEK0IOrcYE6c2GHw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
