---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  KUBECONFORM_SCRIPT: "{{.SCRIPTS_DIR}}/kubeconform.sh"

tasks:

  resources:
    desc: Gather common resources in your cluster, useful when asking for support
    cmds:
      - for: { var: resource }
        cmd: kubectl get {{.ITEM}} {{.CLI_ARGS | default "-A"}}
    vars:
      resource: >-
        nodes
        gitrepositories
        kustomizations
        helmrepositories
        helmreleases
        certificates
        certificaterequests
        ingresses
        pods

  kubeconform:
    desc: Validate Kubernetes manifests with kubeconform
    cmd: bash {{.KUBECONFORM_SCRIPT}} {{.KUBERNETES_DIR}}
    preconditions:
      - { msg: "Missing kubeconform script", sh: "test -f {{.KUBECONFORM_SCRIPT}}" }

  .reset:
    internal: true
    cmd: rm -rf {{.KUBERNETES_DIR}}

  privileged:
    desc: Run a privileged pod
    interactive: true
    cmds:
      - |
        kubectl --context {{.cluster}} run -n {{.namespace}} debug-privileged -i --tty --rm --image=null --privileged --overrides='
          {
            "apiVersion": "v1",
            "spec": {
              "containers": [
                {
                  "name": "debug",
                  "image": "docker.io/library/alpine:latest",
                  "command": [
                    "/bin/bash"
                  ],
                  "stdin": true,
                  "stdinOnce": true,
                  "tty": true
                }
              ],
              {{- if .node }}
              "nodeName": "{{.node}}",
              {{- end }}
              {{- if .hostnetwork }}
              "hostNetwork": true,
              {{- end }}
              "restartPolicy": "Never"
            }
          }'
    vars:
      node: "{{.node | default nil}}"
      namespace: '{{.namespace | default "default"}}'
      hostnetwork: "{{.hostnetwork | default false}}"
      cluster: '{{ or .cluster (fail "Argument (cluster) is required") }}'

  # No good as no ARM build as of yet
  browse-pvc:
    desc: Browse PersistentVolumeClaims
    summary: |
      Args:
        cluster: Cluster to run command against (required)
        ns: Namespace to browse PersistentVolumeClaims in (default: default)
        claim: PersistentVolumeClaim to browse (required)
    interactive: true
    cmd: kubectl browse-pvc --context {{.cluster}} --namespace {{.ns}} {{.claim}}
    requires:
      vars: ["cluster", "claim"]

  delete-failed-pods:
    desc: Deletes pods with a failed status
    summary: |
      Args:
        cluster: Cluster to run command against (required)
    cmds:
      - for: ["Evicted", "Failed", "Succeeded"]
        cmd: kubectl --context {{.cluster}} delete pods --field-selector status.phase={{.ITEM}} -A --ignore-not-found=true
    requires:
      vars: ["cluster"]

  mount-pvc:
    desc: Mount a PersistentVolumeClaim to a temporary pod for a cluster
    summary: |
      Args:
          cluster: Cluster to run command against (required)
          ns: Namespace the PVC is in (default: default)
          claim: PVC to mount (required)
    interactive: true
    cmd: |
      kubectl --context {{.cluster}} run -n {{.ns}} debug-{{.claim}} -i --tty --rm --image=null --privileged --overrides='
        {
          "apiVersion": "v1",
          "spec": {
            "containers": [
              {
                "name": "debug",
                "image": "ghcr.io/onedr0p/alpine:rolling",
                "command": ["/bin/bash"],
                "stdin": true,
                "stdinOnce": true,
                "tty": true,
                "volumeMounts": [
                  {
                    "name": "config",
                    "mountPath": "/config"
                  }
                ]
              }
            ],
            "volumes": [
              {
                "name": "config",
                "persistentVolumeClaim": {
                  "claimName": "{{.claim}}"
                }
              }
            ],
            "restartPolicy": "Never"
          }
        }'
    vars:
      cluster: '{{ or .cluster (fail "Argument (cluster) is required") }}'
      ns: '{{.ns | default "default"}}'
      claim: '{{ or .claim (fail "Argument (claim) is required") }}'
    preconditions:
      - { msg: "PVC not found", sh: "kubectl --context {{.cluster}} -n {{.ns}} get persistentvolumeclaim {{.claim}}" }
